name : ci

on:
  pull_request:
    branches: [main]

jobs: 
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pylint
      
      - name: Lint with pylint
        run: |
          source venv/bin/activate
          pylint --recursive=y ./